services:
  crimsoncls:
    container_name: crimsoncls
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - SERVE_STATIC=1
    restart: unless-stopped
